### ISSUE TITLE
请问行情是否可以通过行情服务器自动获取？

### ISSUE THREAD

**Issue by rwayan** [dearleeyoung/LocalCTP#1]
现在是必须要RegisterFensUserInfo函数投喂嘛？这样的话，还需要该客户端的代码才能正常使用LocalCTP，是否可以改成是人工设定一个行情服务器以后，LocalCTP自己去获取这个行情。

**Comment by dearleeyoung** [comment]
LocalCTP承诺不联网，去连接网络获取行情违背了这个初衷。

**Comment by dearleeyoung** [comment]
行情现在可以通过 `ReqOrderInsert `和 `RegisterFensUserInfo `这两个接口来投喂，前者更适合 java/python 等语言使用，后者由于涉及到指针转换等操作，更适合 C++语言使用。
如果需要通过其他形式获取行情数据，可以自行实现哦。

**Comment by dearleeyoung** [comment]
O(∩_∩)O
