### ISSUE TITLE
是否考虑合约信息, 手续费,保证金 通过实盘账户查询, 这样本地就不用自己维护了

### ISSUE THREAD

**Issue by xibaoning** [dearleeyoung/LocalCTP#2]
如题, 维护麻烦, 而且容易出错, 仿真也不太真了,  如果能通过自己的实盘账号自动化获取那些信息就好了

**Comment by dearleeyoung** [comment]
可将这些数据保存到数据库中并读取。保存和读取的接口都在 `LocalCTP/auto_generated_code/CTPSQLWrapper.h `中，即各个CTP的 struct的SQL Wrapper 类中，使用很方便。
读取解析接口(准确的说是从SQL查询结果中解析的接口):  `XXWrapper::parseFromSqlValue`
写入接口(准确的说是获取写入的SQL语句的接口):  `XXWrapper::generateInsertSql`

**Comment by dearleeyoung** [comment]
O(∩_∩)O

**Comment by dearleeyoung** [comment]
合约信息，手续费率，保证金率，这三种信息现在已经放到数据库中管理了，分别对应各自的表，可以更新数据库的这些数据来让LocalCTP获取
